### ISSUE TITLE
3.5.99.4 FTBFS on EPEL6

### ISSUE THREAD

**Issue by mikedep333** [ArcticaProject/nx-libs#388] opened 2017-03-09 02:42 UTC
See build.log.gz [here.](https://copr-be.cloud.fedoraproject.org/results/mikedep333/nx-libs-3.6/epel-6-x86_64/00523875-nx-libs/)

In particular:
> rm -f ks_tables.h makekeys makekeys.o
gcc -o makekeys -g -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fno-strict-aliasing -g -std=c99 -Wall -Wpedantic -Wpointer-arith -Wundef    -I../.. -I../../exports/include   -Dlinux -D__amd64__ -D_POSIX_C_SOURCE=199309L 				-D_POSIX_SOURCE -D_XOPEN_SOURCE 				-D_DEFAULT_SOURCE                                 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 				 -D_GNU_SOURCE 				  -DFUNCPROTO=15 -DNARROWPROTO -DXTHREADS  -D_REENTRANT -DXUSE_MTSAFE_API    -DMALLOC_0_RETURNS_NULL  -DHAS_SNPRINTF -DLIBX11			-DPOSTLOCALELIBDIR=\"lib\" -I../../../nxcomp -DNX_TRANS_SOCKET              -DNX_TRANS_EXIT -DXCMS -DUSE_XCB=0  -Wl,-z,relro util/makekeys.c  -lpthread   -Wl,-rpath,/usr/lib/nx/X11 -Wl,-rpath-link,../../exports/lib
> cc1: error: unrecognized command line option "-Wpedantic"

**Comment by Ionic** [comment] 2017-03-09 08:08
Duplicate of #282.

**Closed as completed by Ionic** 2017-03-09 08:08 UTC
