### ISSUE TITLE
XFCE Window Manager crashes on nx-libs 3.6 with libNX_X11

### ISSUE THREAD

**Issue by mikedep333** [ArcticaProject/nx-libs#420] opened 2017-04-08 12:30 UTC
[Bug 1433420 - [abrt] xfwm4: XGetXCBConnection(): xfwm4 killed by SIGSEGV](https://bugzilla.redhat.com/show_bug.cgi?id=1433420)

The original report reproduced it on F25. I reproduced it on F26 alpha. I can confirm that Fedora's nx-libs 3.5 is not affected.

nx-libs 3.6 is being built with our upstream .spec file:

https://copr.fedorainfracloud.org/coprs/mikedep333/nx-libs-3.6/

**Comment by Ionic** [comment] 2017-04-08 12:35
Are you mixing up 3.6 and 3.5? This problem should occur with 3.5 but NOT 3.6. For 3.5, there's not much I can do short of a Xinerama backport, which might be pretty complicated by now.

**Comment by Ionic** [comment] 2017-04-08 12:51
Also, make sure that you're using the nightly x2goserver version and that you have installed x2goserver-x2goagent when testing with 3.6. Otherwise that issue will occur with 3.6, naturally.

**Comment by uli42** [comment] 2017-05-05 21:11
Well, clients like xfce should never see the libraries provided by nx. Only nxagent/x2goagent should see them. So I guess Ionic is right: the bug reporter is using an old x2goserver with new nx-libs which will lead to LD_LIBRARY_PATH being set wrong within the session. Any client will then mix up libNX_X11 (as libX11) with the X libraries of the system. Some of them try to use XCB and libNX_X11 does not provide that. The result is a crash...

As this bug is closed at redhat what should we do with it?

Update: I have informed the bug reporter by email.

**Comment by sunweaver** [comment] 2017-05-06 07:13
closing, for reason given above. Not a bug in nx-libs.

**Closed as completed by sunweaver** 2017-05-06 07:13 UTC
