### ISSUE TITLE
libXcomp.so.3: undefined symbol: pthread_key_create

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#756] opened 2019-01-04 11:27 UTC
14:53 < oe1skw> hello, can anyone help me with an x2go problem on ubuntu : /usr/bin/nxproxy: symbol lookup error: /usr/lib/x86_64-linux-gnu/libXcomp.so.3: undefined symbol: pthread_key_create

**Comment by sunweaver** [comment] 2019-03-01 15:50
A workaround for the DEB builds has been applied to the 3.5.99.19 release: https://github.com/ArcticaProject/nx-libs/commit/da9a1bc0b9a42a9f586d5ac0d0392a89f4fe821b

This needs more love and work and better ideas.

@Ionic: Do you think you could take a look at this???

**Comment by sunweaver** [comment] 2019-03-01 22:20
Another finding is that m4/ax_pthread.m4 tests pthread availability and flag usage using gcc, but nxcomp is built using g++.

might it be required to apply a patch like this to ax_pthread.m4?

```
diff --git a/m4/ax_pthread.m4 b/m4/ax_pthread.m4
index 5fbf9fe0d..4d7eddc0c 100644
--- a/m4/ax_pthread.m4
+++ b/m4/ax_pthread.m4
@@ -89,7 +89,6 @@ AC_DEFUN([AX_PTHREAD], [
 AC_REQUIRE([AC_CANONICAL_HOST])
 AC_REQUIRE([AC_PROG_CC])
 AC_REQUIRE([AC_PROG_SED])
-AC_LANG_PUSH([C])
 ax_pthread_ok=no
 
 # We used to check for pthread.h first, but this fails if pthread.h
@@ -481,5 +480,4 @@ else
         ax_pthread_ok=no
         $2
 fi
-AC_LANG_POP
 ])dnl AX_PTHREAD

```

**Comment by Ionic** [comment] 2019-03-24 09:09
This workaround shouldn't be necessary in the first place.

It's essentially what I discovered myself and tried to workaround using `m4/ax_pthread.m4` and explicitly mentioning `$(PTHREAD_LIBS)` or the like in `Makefile.am`.

It only checking the C compiler shouldn't be a problem, though, we're interested in the flags needed to pull-in pthread support.

Something must have changed in between me applying that workaround and the new breakage here?

**Comment by Ionic** [comment] 2019-03-25 04:28
Maybe the thing that changed is actually GCC, i.e., maybe it doesn't need `-lpthread` any longer. I'd have to look up what the variables are set to in a build.

What Debian platforms are affected by this problem exactly? Buster? Sid?

**Comment by sunweaver** [comment] 2019-03-25 06:49
Hi Mihai,

On  Mo 25 Mär 2019 05:28:29 CET, Mihai Moldovan wrote:

> Maybe the thing that changed is actually GCC, i.e., maybe it doesn't  
> need `-lpthread` any longer. I'd have to look up what the variables  
> are set to in a build.

I don't think so. I see the issue with all DEB builds, even on jessie.

This is what you need to look for in the build logs (right at the end):

```
dpkg-shlibdeps: warning: symbol pthread_key_create used by  
debian/libxcomp3/usr/lib/i386-linux-gnu/libXcomp.so.3.5.99 found in  
none of the libraries
dpkg-shlibdeps: warning: symbol pthread_setspecific used by  
debian/libxcomp3/usr/lib/i386-linux-gnu/libXcomp.so.3.5.99 found in  
none of the libraries
dpkg-shlibdeps: warning: symbol pthread_sigmask used by  
debian/libxcomp3/usr/lib/i386-linux-gnu/libXcomp.so.3.5.99 found in  
none of the libraries
dpkg-shlibdeps: warning: symbol pthread_getspecific used by  
debian/libxcomp3/usr/lib/i386-linux-gnu/libXcomp.so.3.5.99 found in  
none of the libraries
dpkg-shlibdeps: warning: symbol pthread_key_delete used by  
debian/libxcomp3/usr/lib/i386-linux-gnu/libXcomp.so.3.5.99 found in  
none of the libraries
```

> What Debian platforms are affected by this problem exactly? Buster? Sid?

jessie -> sid, trusty -> bionic (check build 23 of nx-libs on  
jenkins.arctica-project.org).

In fact, enforcing -lpthread resolves the issue:
https://cgit.arctica-project.org/nx-libs/commit/?id=da9a1bc0b9a42a9f586d5ac0d0392a89f4fe821b

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Ionic** [comment] 2019-03-25 06:54
Weird... that's what I've essentially done in 1c6c9c04b and it used to work. So something must have changed. AFAIK, `$(PTHREAD_LIBS)` contained `-lpthread` back then when I tested.

**Comment by Ionic** [comment] 2019-03-25 07:12
I can't find any mention of `-lpthread` in the X2Go builder that goes back to Nov 2018, though. It must be a regression though, since otherwise we'd been flooded by bug reports and that wasn't the case.

Doesn't help, I'll probably have to look directly into a fully build directory tree and see what `AX_PTHREAD` detected exactly.

**Comment by sunweaver** [comment] 2019-03-25 07:21
Hi Mihai,

thanks for digging into this once more!!!

On  Mo 25 Mär 2019 08:12:29 CET, Mihai Moldovan wrote:

> I can't find any mention of `-lpthread` in the X2Go builder that  
> goes back to Nov 2018, though. It must be a regression though, since  
> otherwise we'd been flooded by bug reports and that wasn't the case.
>
> Doesn't help, I'll probably have to look directly into a fully build  
> directory tree and see what `AX_PTHREAD` detected exactly.

This I found relevant when looking into things:
https://stackoverflow.com/questions/17055279/autotools-for-pthreads-not-setting-correct-linker-flags

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Ionic** [comment] 2019-03-25 08:20
I can't say when I manage to really look into that, though, since I now have another problem with X2Go Client on OS X not being able to connect to one of my machines (but another one works), so I'll have to debug libssh first...

**Comment by Ionic** [comment] 2019-04-01 07:01
Okay, I now understand the problem a little bit better: this is an issue that I never **really** fixed, just worked around for `nxproxy`.

So, the base line issue is that `libXcomp` never linked against `libpthread`. That's bad and lead to `nxproxy` failing. I looked around, found that `libtool` bug and it fit the description quite well. I then discovered `AX_PTHREAD` in the autotools archive and employed it in `libXcomp` at first. Afterwards, Uli reported that `nxproxy` was still failing to launch and that we'll need to link it against `libpthread`. This struck me odd, because `nxproxy` itself shouldn't need to link against `libpthread` anyway if it's not using any pthread functions - `libXcomp` should link against it and hence `libpthread` be linked at startup anyway.

So:
  - `libXcomp` didn't link against `libpthread`
  - neither did `nxproxy`
  - discovered `AX_PTHREAD`, used within `libXcomp` thinking that it would finally link against `libpthread` with that
  - didn't, so added `AX_PTHREAD` usage to `nxproxy` which looked to work fine
  - now this report
  - all build logs report missing symbols (even for old `nx-libs` versions)

What I _failed_ to realize back then is that `libXcomp` never properly linked against `libpthread` (due to the mentioned `libtool` bug) and `AX_PTHREAD` not (directly) helping in that case. Making `nxproxy` use `AX_PTHREAD` worked around that issue for `nxproxy`, because this tool is compiled with a C compiler that doesn't show the `libtool` bug (i.e., `libtool` doesn't try to link C objects with `-nostdlib`).

What I don't quite understand so far is why `nxproxy` seems only to fail to start on Ubuntu. It's loading up `libpthread` so `libXcomp` should be working fine within `nxproxy`. The linking order doesn't seem to matter (at least not in that case), so it should just work - like it does on other distros. Maybe something is special about that distro or system.

In any case, we still have the underlinking bug for `libXcomp` and an overlinking bug for `nxproxy` and maybe `nxagent`.

I'll try to figure out how to correctly force `AX_PTHREAD` to use the direct linking flags for `libXcomp`.

**Comment by sunweaver** [comment] 2019-04-01 08:15
Hi Mihai,

On  Mo 01 Apr 2019 09:01:25 CEST, Mihai Moldovan wrote:

> Okay, I now understand the problem a little bit better: this is an  
> issue that I never **really** fixed, just worked around for `nxproxy`.
>
> So, the base line issue is that `libXcomp` never linked against  
> `libpthread`. That's bad and lead to `nxproxy` failing. I looked  
> around, found that `libtool` bug and it fit the description quite  
> well. I then discovered `AX_PTHREAD` in the autotools archive and  
> employed it in `libXcomp` at first. Afterwards, Uli reported that  
> `nxproxy` was still failing to launch and that we'll need to link it  
> against `libpthread`. This struck me odd, because `nxproxy` itself  
> shouldn't need to link against `libpthread` anyway if it's not using  
> any pthread functions - `libXcomp` should link against it and hence  
> `libpthread` be linked at startup anyway.
>
> So:
>   o `libXcomp` didn't link against `libpthread`
>   o neither did `nxproxy`
>   o discovered `AX_PTHREAD`, used within `libXcomp` thinking that it  
> would finally link against `libpthread` with that
>   o didn't, so added `AX_PTHREAD` usage to `nxproxy` which looked to  
> work fine
>   o now this report
>   o all build logs report missing symbols (even for old `nx-libs` versions)
>
> What I _failed_ to realize back then is that `libXcomp` ne ver  
> properly linked against `libpthread` (due to the mentioned `libtool`  
> bug) and `AX_PTHREAD` not (directly) helping in that case. Making  
> `nxproxy` use `AX_PTHREAD` worked around that issue for `nxproxy`,  
> because this tool is compiled with a C compiler that doesn't show  
> the `libtool` bug (i.e., `libtool` doesn't try to link C objects  
> with `-nostdlib`).
>
> What I don't quite understand so far is why `nxproxy` seems only to  
> fail to start on Ubuntu. It's loading up `libpthread` so `libXcomp`  
> should be working fine within `nxproxy`. The linking order doesn't  
> seem to matter (at least not in that case), so it should just work -  
> like it does on other distros. Maybe something is special about that  
> distro or system.
>
> In any case, we still have the underlinking bug for `libXcomp` and  
> an overlinking bug for `nxproxy` and maybe `nxagent`.
>
> I'll try to figure out how to correctly force `AX_PTHREAD` to use  
> the direct linking flags for `libXcomp`.

I fully agree with your analysis. I came to the same conclusion / assumptions.

I read somewhere, that g++ with -nostdlib ignores -pthread in the  
linker and thus a -lpthread is required, but AX_PTHREAD.m4 does not  
cover that corner case. Furthermore, AX_PTHREAD uses a C compiler for  
code tests, not a C++ compiler.

Maybe that helps...

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Ionic** [comment] 2019-04-04 07:47
I've been looking into this, thinking about it and came up with the following:

  - `AX_PTHREAD` forcefully using C to test is not a problem. It just makes checking for pthread stuff easier, because:
    - No actual variables are changed, users of `AX_PTHREAD` are supposed to use the special variables `$PTHREAD_CC`, `$PTHREAD_CFLAGS` and `$PTHREAD_LIBS` and add them to respective variables.
    - `LDFLAGS` are language-agnostic by design.
    - It's assumed that the general `pthread` flags are available for any programming language/backend as well.
    - Not setting a specific language would blow up the code with checks for the language and modifying specific variables like `CFLAGS`, `CXXFLAGS`, `FFLAGS`, `FCFLAGS`, `ERLCFLAGS`, `OBJCFLAGS` or `OBJCXXFLAGS` all over the place.
  - *Any* language for which `-nostdlib` (so... probably all of them) is supported are affected - not just C++. It's just rarely/never used by libtool in C mode.
  - This is not a problem in `AX_PTHREAD` but actually `libtool`, so the bug should be fixed in libtool. This said, we can't patch and rebuild `libtool` on affected systems, the upstream patch is both wrong (would work on Linux with glibc, but not with libc variants or operating systems that do not have `libpthread.so`), is not incorporated yet anyway and even if all these points were fixed, it would only work correctly on systems with recent/fixed `libtool` versions. Alternatively, we could patch `ltmain.sh`, but that's impossible since we want `nx-libs` to run on other platforms than Linux/glibc, so `ltmain.sh` will not have a determinable content. Not going to happen.
  - To correctly workaround-fix that in `AX_PTHREAD`, we'd have to know how the actual compilation is being done later. Importantly, if the system will ever use `-nostdlib`. Since we don't have crystal ball, we can't go this route and instead have to catch corner cases preemptively.
  - The best way to do this preemptive workaround would be to extend the `-pthread` check with another check that uses two-stage compilation (`AX_PTHREAD` also does that in case `clang` is being used to figure out how to work around warning messages that only show up in two-stage compilation) with `-nostdlib` added to the CFLAGS. However, that's not easily possible to do. `-nostdlib` *really* disables usage of all system libraries *and* internal objects. `libtool` goes through great lengths to figure out what objects and libraries to link in `-nostdlib` mode by compiling/linking a simple test program and extracting the required information out of the linker's verbose output. It would be insane to copy hundreds of lines from `libtool` into `AX_PTHREAD` just for that.
  - Next best thing: if using `gcc`, check if `libpthread` can be linked/exists using a trivial test program that *does* use a pthread symbol (otherwise the test would be meaningless with `--as-needed`). If that links correctly, we can just add `-lpthread` to `$PTHREAD_LIBS`.

The only way this would still lead to problems is if users specify a C compiler that is not `gcc` (e.g., `clang`), but a different language compiler that is part of the GCC suite. It's not *completely* unreasonable to do so, for instance when using `clang(++)` for C and C++ code, but `gfortran` for Fortran97 code or the like. Not that we'd do, but I guess I should try to push any changes to `AX_PTHREAD` upstream, so I should consider it. I'd argue that this doesn't break any behavior that wasn't broken before, so we're good.

**Comment by sunweaver** [comment] 2019-04-04 08:04
On  Do 04 Apr 2019 09:47:41 CEST, Mihai Moldovan wrote:

>   - Next best thing: if using `gcc`, check if `libpthread` can be  
> linked/exists using a trivial test program that *does* use a pthread  
> symbol (otherwise the test would be meaningless with `--as-needed`).  
> If that links correctly, we can just add `-lpthread` to  
> `$PTHREAD_LIBS`.

This sounds like the way to go. It is basically what I did "by-hand".  
Assuming gcc is used, assuming libpthread exists and is linkable  
against and thus add -lpthread on all DEB related builds.

> The only way this would still lead to problems is if users specify a  
> C compiler that is not `gcc` (e.g., `clang`), but a different  
> language compiler that is part of the GCC suite. It's not  
> *completely* unreasonable to do so, for instance when using  
> `clang(++)` for C and C++ code, but `gfortran` for Fortran97 code or  
> the like. Not that we'd do, but I guess I should try to push any  
> changes to `AX_PTHREAD` upstream, so I should consider it. I'd argue  
> that this doesn't break any behavior that wasn't broken before, so  
> we're good.

Yep. Sounds sensible. Thanks for the thorough investigation. Will you  
have time to work on that patch?

Mike
-- 

DAS-NETZWERKTEAM
c\o Technik- und Ökologiezentrum Eckernförde
Mike Gabriel, Marienthaler str. 17, 24340 Eckernförde
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by Ionic** [comment] 2019-04-04 08:34
I'm doing so right now. Somehow, hardcoding `-lpthread` also sounds wrong because the library might be called differently on some systems (like `libpthreads`). Worse than that, some system even seem have both libraries around, although one of them is non-POSIX. I guess I should scan the list for libraries and test that until a suitable one is found.

**Comment by uli42** [comment] 2019-04-04 08:53
On Thu, Apr 4, 2019 at 10:34 AM Mihai Moldovan <notifications@github.com> wrote:
>
> I'm doing so right now. Somehow, hardcoding -lpthread also sounds wrong because the library might be called differently on some systems (like libpthreads). Worse than that, some system even seem have both libraries around, although one of them is non-POSIX. I guess I should scan the list for libraries and test that until a suitable one is found.

To me this sounds like a problem that many people should have. So are
you sure there's no upstream solution to this?

Uli

**Comment by Ionic** [comment] 2019-04-04 08:56
`AX_PTHREAD` naturally supports that and manages its internal list in a smart way to avoid such problems.

**Closed as completed** 2019-04-07 19:36 UTC
