### ISSUE TITLE
segfault in libXcomp when accessing OPSI's configed Java Application (running as Java Plugin)

### ISSUE THREAD

**Issue by sunweaver** [ArcticaProject/nx-libs#74] opened 2016-01-21 11:13 UTC
Jan 21 11:48:03 tjener kernel: [91649.121408] x2goagent[19500]: segfault at 741c000 ip 00007fb26ab501e0 sp 00007ffe87978e48 error 4 in libXcomp.so.3.5.99.0[7fb26aafa000+e8000]

Using Oracle-Java8 Version 8.72 inside Iceweasel ESR 38.5.0.

**Comment by iagomez** [comment] 2017-11-07 21:43
Hello,

I believe we're seeing this bug in our environment:

**OS:** Red Hat Enterprise Linux Server release 7.3 (Maipo)

**RPM Versions:**
```
:~ # rpm -qa | grep -Pi "(nx|x2go)"
libNX_X11-3.5.0.32-3.el7.x86_64
libNX_Xtst-3.5.0.32-3.el7.x86_64
libNX_Xcomposite-3.5.0.32-3.el7.x86_64
libNX_Xdmcp-3.5.0.32-3.el7.x86_64
libNX_Xext-3.5.0.32-3.el7.x86_64
libNX_Xrender-3.5.0.32-3.el7.x86_64
libNX_Xinerama-3.5.0.32-3.el7.x86_64
nxagent-3.5.0.32-3.el7.x86_64
nx-libs-3.5.0.32-3.el7.x86_64
libNX_Xdamage-3.5.0.32-3.el7.x86_64
libNX_Xrandr-3.5.0.32-3.el7.x86_64
libNX_Xpm-3.5.0.32-3.el7.x86_64
x2goagent-3.5.0.32-3.el7.x86_64
x2goserver-4.0.1.20-1.el7.x86_64
libNX_Xfixes-3.5.0.32-3.el7.x86_64
```

**Segfault messages**
```
agmrkgridlogin2:~ # zgrep -i segfault /var/log/messages*
/var/log/messages-20171023.gz:Oct 16 10:30:56 agmrkgridlogin2 kernel: x2goagent[13951]: segfault at 3fa94e0 ip 00007efc6c668bd0 sp 00007fff6640e658 error 4 in libXcomp.so.3.5.0.32[7efc6c611000+ec000]
/var/log/messages-20171029.gz:Oct 24 11:59:34 agmrkgridlogin2 kernel: x2goagent[12860]: segfault at 3f24000 ip 00007f74762febd0 sp 00007ffcac9e3dd8 error 4 in libXcomp.so.3.5.0.32[7f74762a7000+ec000]
/var/log/messages-20171029.gz:Oct 25 21:08:34 agmrkgridlogin2 kernel: x2goagent[23812]: segfault at 5ec353a ip 00007f39ad887bd0 sp 00007ffd29c0dd08 error 4 in libXcomp.so.3.5.0.32[7f39ad830000+ec000]
/var/log/messages-20171029.gz:Oct 25 21:11:24 agmrkgridlogin2 kernel: x2goagent[9404]: segfault at 3239000 ip 00007f6bb1760bd0 sp 00007ffeb7140248 error 4 in libXcomp.so.3.5.0.32[7f6bb1709000+ec000]
/var/log/messages-20171029.gz:Oct 26 10:27:00 agmrkgridlogin2 kernel: x2goagent[4849]: segfault at 2e99000 ip 00007efccbe5abd0 sp 00007ffec5333918 error 4 in libXcomp.so.3.5.0.32[7efccbe03000+ec000]
/var/log/messages-20171029.gz:Oct 26 10:27:31 agmrkgridlogin2 kernel: x2goagent[6292]: segfault at 36433c0 ip 00007f4a55b36bd0 sp 00007ffc03681ab8 error 4 in libXcomp.so.3.5.0.32[7f4a55adf000+ec000]
/var/log/messages-20171029.gz:Oct 26 10:29:57 agmrkgridlogin2 kernel: x2goagent[10705]: segfault at 1b9b052 ip 00007fa01d1d5bd0 sp 00007ffd99434628 error 4 in libXcomp.so.3.5.0.32[7fa01d17e000+ec000]
/var/log/messages-20171029.gz:Oct 26 10:30:37 agmrkgridlogin2 kernel: x2goagent[19325]: segfault at 36cd000 ip 00007f09493f4bd0 sp 00007ffc208a5398 error 4 in libXcomp.so.3.5.0.32[7f094939d000+ec000]
/var/log/messages-20171105.gz:Nov  4 08:22:02 agmrkgridlogin2 kernel: x2goagent[10405]: segfault at 2148daa ip 00007fa98f690bd0 sp 00007ffc0d668688 error 4 in libXcomp.so.3.5.0.32[7fa98f639000+ec000]
```

Is it possible to confirm if this is the same root cause and also any workarounds?

Thanks!

**Comment by uli42** [comment] 2017-11-07 22:31
Difficult to say

**Comment by uli42** [comment] 2020-01-15 22:52
this is for old nx-libs 3.5.0.32, so I would rather close this.

**Comment by sunweaver** [comment] 2020-01-16 05:19
hi,

Am Mittwoch, 15. Januar 2020 schrieb Ulrich Sibiller:
> this is for old nx-libs 3.5.0.32, so I would rather close this.
> 

ok, please do.

Mike

-- 
Gesendet von meinem Sailfish Gerät

**Closed as completed** 2020-01-16 09:19 UTC
Labels: bug
