### ISSUE TITLE
Not able to disable Xinerama 

### ISSUE THREAD

**Issue by HolySephi** [ArcticaProject/nx-libs#117] opened 2016-04-25 10:54 UTC
While debugging another issue we encountered the problem that we were unable to turn off the new xinerama feature. Neither "-xinerama" nor "-extension XINERAMA" disables Xinerama.

Steps to reproduce:

`/usr/bin/nxagent -extension XINERAMA :1`

In any combination you are trying you get the same message from the new xinerama-Code:

```
nxagentAdjustRandRXinerama: Xinerama is disabled
nxagentAdjustRandRXinerama: faking xinerama
nxagentAdjustRandRXinerama: numCrtcs [0], numOutputs [0]
nxagentAdjustRandRXinerama: RRGetInfo returned [1]
nxagentAdjustRandRXinerama: bounding box: left [8] right [2888] top [213] bottom[1023]
nxagentAdjustRandRXinerama: numCrtcs [1], numOutputs [1]
nxagentAdjustRandRXinerama: numCrtcs [1], numOutputs [1]
nxagentAdjustRandRXinerama: destroying output [default]
nxagentAdjustRandRXinerama: created new output [NX1]
nxagentAdjustRandRXinerama: adjusting output [NX1]
nxagentAdjustRandRXinerama: output 0: prevmode [2880x810] ([0x1819200]) refcnt [2]
nxagentAdjustRandRXinerama: output 0: intersection is x [0] y [0] width [2880] height [810]
nxagentAdjustRandRXinerama: output 0: mode [nx_2880x810] ([0x1819360]) created/received, refcnt [2]
nxagentAdjustRandRXinerama: setting mode [nx_2880x810] ([0x1819360]) refcnt [2] for output 0
nxagentAdjustRandRXinerama: setting mode [nx_2880x810] ([0x1819360]) refcnt [2] for crtc 0
nxagentAdjustRandRXinerama: destroying prevmode [2880x810]
nxagentAdjustRandRXinerama: crtc 0 has mode [nx_2880x810] ([0x1819360]), refcnt [3] and 1 outputs
                            output[0]->crtc=[0x18184c0]
nxagentAdjustRandRXinerama: Min 320x240, Max 3840x1200
```

**Comment by uli42** [comment] 2016-04-25 11:35
On Mon, Apr 25, 2016 at 12:54 PM, Florian Wicke
notifications@github.com wrote:

> While debugging another issue we encountered the problem that we were unable
> to turn off the new xinerama feature. Neither "-xinerama" nor "-extension
> XINERAMA" disables Xinerama.

If at the time of session creation the real xserver does not offer
Xinerama it gets enabled in nxagent nevertheless because at reconnect
time the real xserver might offer xinerama and we cannot enable it on
the fly (although - thinking about it it might be possible to activate
an extension at a later time. Need to check). So we always enable
xinerama. -xinerama or -extension XINERAMA should result in _one_
screen or monitor within the session, no matter what is outside.

Do you have a specific need for the extension beeing disabled?

Uli

**Comment by HolySephi** [comment] 2016-04-25 11:39
sunweaver suggested to disable the xinerama code while debugging #118 and it was not working thus he advised me to file this as a seperate bug. If it is intentional to never be able to disable the xinerama code then don't mind my bugreport on this.

**Comment by uli42** [comment] 2016-04-25 11:49
Ok, then I'll close this for now..

BTW: there was this option -disablexineramaextension that might work if you really need to disable Xinerama. Not sure if it is still there in the current 3.6.0 version.

**Comment by uli42** [comment] 2016-04-26 08:00
Reopening. 

Currently you can disable XINERAMA only by also disabling RANDR (-extension RANDR). Do we need a solution where XINERAMA can be disabled independently?

**Comment by HolySephi** [comment] 2016-04-26 08:46
Maybe as sunweaver suggested for debugging purposes - as #118 states we encounter segmentation faults and by observing the crash my best guess is that it fails on setting the (new) resolution on resume. Being able to turn off single features could help in identifying the cause of problems.

**Comment by uli42** [comment] 2016-04-26 09:04
You can disable that code by specifying -extension RANDR. If you want to keep RANDR and disable XINERAMA only that is not possible currently and regarding your suspicion will not help as the XINERAMA stuff is coming from RANDR. There's a separate XINERAMA extension in the code but that one is not used.

**Comment by HolySephi** [comment] 2016-04-26 09:15
starting nxagent with
`nxagent -extension RANDR :1`
does nothing - the randr/xinerma stuff is loaded anyway:

```
root@LTS ~ # nxagent -extension RANDR :1

NXAGENT - Version 3.5.99.0

Copyright (C) 2001, 2011 NoMachine.
See http://www.nomachine.com/ for more information.

Info: Agent running with pid '30398'.
Session: Starting session at 'Tue Apr 26 11:10:55 2016'.
nxagentSetScreenSaverTime: ScreenSaverTime was [600000], ScreenSaverInterval was [600000].
nxagentSetScreenSaverTime: ScreenSaverTime now is [600000], ScreenSaverInterval now is [600000].
nxagentSetScreenInfo: Server image order is [0] bitmap order is [0].
nxagentSetScreenInfo: Server scanline unit is [32] scanline pad is [32].
nxagentSetPixmapFormats: Set format at index [0] to depth [1] bits per pixel [1] scanline pad [32].
nxagentSetPixmapFormats: Set format at index [1] to depth [4] bits per pixel [8] scanline pad [32].
nxagentSetPixmapFormats: Set format at index [2] to depth [8] bits per pixel [8] scanline pad [32].
nxagentSetPixmapFormats: Set format at index [3] to depth [15] bits per pixel [16] scanline pad [32].
nxagentSetPixmapFormats: Set format at index [4] to depth [16] bits per pixel [16] scanline pad [32].
nxagentSetPixmapFormats: Set format at index [5] to depth [24] bits per pixel [32] scanline pad [32].
nxagentSetPixmapFormats: Set format at index [6] to depth [32] bits per pixel [32] scanline pad [32].
nxagentOpenScreen: Called for screen index [0].
Debug: Setting up visuals. Original array has size [63].
Debug: Set default visual index [0].
Debug: Added visual [32].
Debug: Registered visual [32] for depth [0 (24)].
Debug: Added visual [63].
Debug: Registered visual [63] for depth [0 (24)].
Debug: Setting default visual [0 (32)].
Debug: Setting root depth [24].
nxagentOpenScreen: Frame buffer allocated. rootDepth [24] bitsPerPixel [32] sizeInBytes [37324800]
nxagentOpenScreen: Before fbScreenInit numVisuals [2] numDepths [7] rootDepth [24] defaultVisual [140724603453472].
nxagentOpenScreen: After fbScreenInit numVisuals [2] numDepths [7] rootDepth [24] defaultVisual [140724603453472].
nxagentOpenScreen: Before GLX numVisuals [2] numDepths [7] rootDepth [24] defaultVisual [140724603453472].
nxagentOpenScreen: After GLX numVisuals [8] numDepths [7] rootDepth [24] defaultVisual [140724603453556].
nxagentOpenScreen: Going to initialize backing store.
Info: Using alpha channel in render extension.
nxagentOpenScreen: Root window at offset (0,0) size (2880,810).
nxagentOpenScreen: Default window at offset (0,0) size (2880,810) border size 0.
nxagentOpenScreen: Span between root window and default window is (0,0).
nxagentOpenScreen: Default window in window mode has offset (0,0) and size (2880,810).
nxagentOpenScreen: Fullscreen is OFF.
nxagentOpenScreen: Desktop resize mode is ON.
nxagentOpenScreen: Resize desktop at startup is OFF.
nxagentOpenScreen: Going to create new default window.
nxagentOpenScreen: Created new default window with id [8388686].
nxagentOpenScreen: Setting WM_CLASS and WM_NAME for window withid [8388686].
nxagentOpenScreen: Found WM, delete window atom [237].
Info: Not using local device configuration changes.
SessionPath not defined
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Error:            Cannot open "compiled/server-1.xkm" to write keyboard description
>                   Exiting
nxagentSaveScreen: Called for screen at [0x20e9d50] with parameter [2].
nxagentSaveScreen: SCREEN_SAVER_ON is [0] SCREEN_SAVER_OFF is [1] SCREEN_SAVER_FORCER is [2] SCREEN_SAVER_CYCLE is [3].
Session: Session started at 'Tue Apr 26 11:10:57 2016'.
nxagentChangeScreenConfig: WindowTable[0] is 0x211a450
nxagentChangeScreenConfig: Changing config to 2880x810.
--------------- Before Resize Screen -----------------.
nxagentResizeScreen: Root window at offset (0,0) size (2880,810).
nxagentResizeScreen: Default window at offset (8,57) size (2880,810) border size 0.
nxagentResizeScreen: Span between root window and default window is (0,0).
nxagentResizeScreen: Default window in window mode has offset (0,0) and size (2880,810).
nxagentResizeScreen: Fullscreen is OFF.
nxagentResizeScreen: Desktop resize mode is ON.
nxagentResizeScreen: Resize desktop at startup is OFF.
--------------- After Resize Screen -----------------.
nxagentResizeScreen: Root window at offset (0,0) size (2880,810).
nxagentResizeScreen: Default window at offset (8,57) size (2880,810) border size 0.
nxagentResizeScreen: Span between root window and default window is (0,0).
nxagentResizeScreen: Default window in window mode has offset (0,0) and size (2880,810).
nxagentResizeScreen: Fullscreen is OFF.
nxagentResizeScreen: Desktop resize mode is ON.
nxagentResizeScreen: Resize desktop at startup is OFF.
nxagentAdjustRandRXinerama: Xinerama is disabled
nxagentAdjustRandRXinerama: faking xinerama
nxagentAdjustRandRXinerama: numCrtcs [0], numOutputs [0]
nxagentAdjustRandRXinerama: RRGetInfo returned [1]
nxagentAdjustRandRXinerama: bounding box: left [8] right [2888] top [57] bottom[867]
nxagentAdjustRandRXinerama: numCrtcs [1], numOutputs [1]
nxagentAdjustRandRXinerama: numCrtcs [1], numOutputs [1]
nxagentAdjustRandRXinerama: destroying output [default]
nxagentAdjustRandRXinerama: created new output [NX1]
nxagentAdjustRandRXinerama: adjusting output [NX1]
nxagentAdjustRandRXinerama: output 0: prevmode [2880x810] ([0x21db080]) refcnt [2]
nxagentAdjustRandRXinerama: output 0: intersection is x [0] y [0] width [2880] height [810]
nxagentAdjustRandRXinerama: output 0: mode [nx_2880x810] ([0x21db1e0]) created/received, refcnt [2]
nxagentAdjustRandRXinerama: setting mode [nx_2880x810] ([0x21db1e0]) refcnt [2] for output 0
nxagentAdjustRandRXinerama: setting mode [nx_2880x810] ([0x21db1e0]) refcnt [2] for crtc 0
nxagentAdjustRandRXinerama: destroying prevmode [2880x810]
nxagentAdjustRandRXinerama: crtc 0 has mode [nx_2880x810] ([0x21db1e0]), refcnt [3] and 1 outputs
                            output[0]->crtc=[0x21da340]
nxagentAdjustRandRXinerama: Min 320x240, Max 3840x1200
nxagentChangeScreenConfig: Geometry: 8,57 2880x810
nxagentChangeScreenConfig: return 1
Info: Screen [0] resized to geometry [2880x810] fullscreen [0].
```

**Comment by sunweaver** [comment] 2016-04-26 14:29
Hi Uli,

On  Mo 25 Apr 2016 13:35:00 CEST, Ulrich Sibiller wrote:

> On Mon, Apr 25, 2016 at 12:54 PM, Florian Wicke
> notifications@github.com wrote:
> 
> > While debugging another issue we encountered the problem that we were unable
> > to turn off the new xinerama feature. Neither "-xinerama" nor "-extension
> > XINERAMA" disables Xinerama.
> 
> If at the time of session creation the real xserver does not offer
> Xinerama it gets enabled in nxagent nevertheless because at reconnect
> time the real xserver might offer xinerama and we cannot enable it on
> the fly (although - thinking about it it might be possible to activate
> an extension at a later time. Need to check). So we always enable
> xinerama. -xinerama or -extension XINERAMA should result in _one_
> screen or monitor within the session, no matter what is outside.
> 
> Do you have a specific need for the extension beeing disabled?
> 
> Uli

We can enable Xinerama on the fly (i.e., on session resumption).

https://github.com/ArcticaProject/nx-libs/commit/0297567cd501b6fc012c41ff4a1ae27304ff6a10

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by sunweaver** [comment] 2016-04-26 14:30
On  Di 26 Apr 2016 10:00:42 CEST, Ulrich Sibiller wrote:

> Reopening.
> 
> Currently you can disable XINERAMA only by also disabling RANDR  
> (-extension RANDR). Do we need a solution where XINERAMA can be  
> disabled independently?

IMHO, I'd say we want to have it. We want to disable XINERAMA via  
cmdline or via NX option.

The latter should work (not well tested). I always thought the first  
does also work. One is never done with learning new things...

Greets,

## Mike

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by uli42** [comment] 2016-04-26 14:41
Well, while enabling on the fly is technically possible I am totally unsure if that is supported by X11. I have tried to find some hints about late extensions activation but failed. My concerns are applications that ask the xserver once and cache the result (for whatever reason). If that is a defined behaviour in respect to X11 standards we cannot enable the extension on demand.
Also, I know there are *Init() functions but not *Close() functions in the extensions. This is kind of sign that extensions are not designed to be changed at runtime.

To make it clear: -xinerama does not do nothing, it changes the internal behaviour of the randr/xinerama code to not report multiple screens.

**Comment by sunweaver** [comment] 2016-04-26 14:50
Hi Ulrich,

On  Di 26 Apr 2016 16:41:49 CEST, Ulrich Sibiller wrote:

> Well, while enabling on the fly is technically possible I am totally  
> unsure if that is supported by X11. I have tried to find some hints  
> about late extensions activation but failed. My concerns are  
> applications that ask the xserver once and cache the result (for  
> whatever reason). If that is a defined behaviour in respect to X11  
> standards we cannot enable the extension on demand.
> Also, I know there are *Init() functions but not *Close() functions  
> in the extensions. This is kind of sign that extensions are not  
> designed to be changed at runtime.
> 
> To make it clear: -xinerama does not do nothing, it changes the  
> internal behaviour of the randr/xinerama code to not report multiple  
> screens.

Ah. Ok. Maybe we are talking about different things here.

What we (Sephi and I) want is to disable the reporting of multiple  
screens and a screen split by the Xinerama+XRandR code.

This behaviour should be on/off switchable (which should work and  
obviously does with "-xinerama" and the xinerama NX option).

Disabling the extension (-extension XINERAMA) fully should also work,  
but not on the fly. I understand that the original Xinerama extension  
is not loaded (and disabled?) in nxagent. Would it make sense to  
disable the Xinerama code in RandR by -extension XINERAMA?

Or do I think to complicated here?

Mike

## 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Key ID 0x25771B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

freeBusy:
https://mail.das-netzwerkteam.de/mailxchange/kronolith/fb.php?u=m.gabriel%40das-netzwerkteam.de

**Comment by uli42** [comment] 2016-04-26 15:06
So then use -extension RANDR. 

If you want to completely switch off my code there's no way currently, I fear. I'll try to look into that later today.

The XINERAMA part in the RANDR extension can be disabled in the randr code but not in the nxagent code. I 'd prefer to avoid that to keep the number of files changed by nx low.

**Comment by Ionic** [comment] 2016-04-26 16:06
> Also, I know there are *Init() functions but not *Close() functions in the extensions. This is kind of sign that extensions are not designed to be changed at runtime.

That's not really true. While working on the Composite extension, I stumbled upon `AddExtension()`. This function is defined in `nx-X11/programs/Xserver/dix/extension.c`, must be used during extension initialization and explicitly requires a CloseDown procedure, which sets `ext->CloseDown`. I haven't looked further if and how this is used in later code, though.

Newer X.Org Server versions also accept a null pointer passed at that place, though, so I don't know if extension unloading is a general thing.

**Comment by Ionic** [comment] 2016-04-26 16:11
From `nx-X11/programs/Xserver/include/extnsionst.h`:

``` C
typedef struct _ExtensionEntry {
    int index;
    void (* CloseDown)( /* called at server shutdown */
        struct _ExtensionEntry * /* extension */);
    ...
} ExtensionEntry;
```

I think dynamic extension loading and unloading isn't a thing, at least with the old X.Org Server version in NX. I'd have to look at the current X.Org Server master branch to comment on the current state, but I suspect the behavior has not changed (mostly because extension unloading doesn't make a huge amount of sense in normal X.Org Server usage scenarios.)

**Comment by sunweaver** [comment] 2016-06-09 10:04
Looked into this a bit deeper...

We have to differentiate here between XINERAMA's Xinerama (+|-xinerama or +|-extension XINERAMA) implementation and RANDR's Xinerama implementation.

Currently, you can enable / disable XINERAMA's Xinerama with various options:
  +|-extension XINERAMA (cmdline option)
  +|-xinerama (cmdline option, synomous option for +|-extension XINERAMA AFAICT)
  xinerama=0|1 (nx/nx option)

The important thing now is:::

Whenever the XINERAMA extension in nxagent gets disabled, it falls back (defaults to) using RANDR's Xinerama implementation, thus the new code provider by @uli42.

What this ticket is about, that for debugging, but also maybe other (user) purposes it may be helpful to disable the XINERAMA extension _and_ the RANDR Xinerama implementation. This should be possible without having to disable the full RANDR extension.

Proposal:

  -norrxinerama (cmdline option)
  rrxinerama=0|1 (nx/nx option, defaulting to 1)

Comments, thoughts?
Mike

**Comment by sunweaver** [comment] 2016-06-09 10:19
Well... Actually the old XINERAMA extension implementation is broken by design in nxagent.

Just thinking: wouldn't it be better dropping the libXinerama dependency fully and default to rrxinerama always.

We should then "abuse" "+|-xinerama" for enabling/disabling rrxinerama.

We should also "abuse" nx/nx option xinerama=0|1 for enabling/disabling rrxinerama.

Comments, thoughts?
Mike

**Comment by HolySephi** [comment] 2016-06-10 07:22
Yeah, sounds like a good idea - especially only having one xinerama implementation might be good for future debugging/maintaining

**Closed as completed** 2016-06-18 17:50 UTC
